# Configuração global do Traefik
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Configuração de log
log:
  level: INFO

# Configurações de acesso (dashboard)
api:
  dashboard: true
  insecure: false

# Providers - de onde o Traefik obtém configurações
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: ainovar-network
  file:
    directory: "/etc/traefik/config"
    watch: true

# Entrypoints - pontos de entrada das requisições
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Configuração para HTTPS/TLS
certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@ainovar.tech"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: web 